//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWArchitecture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int statistic_id { get; set; }
        public string mark { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<System.DateTime> date_of { get; set; }
    }
}
