//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWArchitecture
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroup
    {
        public int group_id { get; set; }
        public string name { get; set; }
        public Nullable<int> course { get; set; }
        public Nullable<int> specialization_id { get; set; }
    }
}
