//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWArchitecture
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int user_id { get; set; }
        public Nullable<int> user_type_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> group_id { get; set; }
    }
}
