//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWArchitecture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task1
    {
        public int task_id { get; set; }
        public string name { get; set; }
        public string upcode { get; set; }
        public string taskcode { get; set; }
        public string answer { get; set; }
        public string descriptio { get; set; }
        public string relefortask { get; set; }
        public Nullable<int> language_id { get; set; }
        public string downcode { get; set; }
    }
}
